services:
  - type: web
    name: TBSC_hosting1
    env: python
    buildCommand: pip install -r requirements-render.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn logU.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: TBSC_hosting1.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tbsc_db
          property: connectionString

databases:
  - name: tbsc_db
    databaseName: tbsc_db
    user: tbsc_user
